import type { Metadata } from "next";
import "./globals.css";
import CookieConsent from "@/widgets/CookiesConsent";
import { Suspense } from "react";
import Loading from "@/widgets/Loading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className="font-roboto">
        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>
        <CookieConsent />
      </body>
    </html>
  );
}
