import { Inter } from 'next/font/google';
import { Metadata } from 'next';
import Header from '@/widgets/app-home/_ui/Header';
import Footer from '@/widgets/app-home/_ui/Footer';
import { Suspense } from 'react';
import Loading from '@/widgets/Loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Deutschhub',
  description: 'Generated by create next app'
};

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <Suspense fallback={ <Loading /> }>
        {children}
      <Footer />
      </Suspense>
    </>  
  );
}
