apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
    traefik.ingress.kubernetes.io/redirect-entry-point: "websecure"
    traefik.ingress.kubernetes.io/ssl-redirect: "true"
    traefik.ingress.kubernetes.io/secure: "true"
    traefik.ingress.kubernetes.io/proxy-buffer-size: "32k"
    traefik.ingress.kubernetes.io/proxy-connect-timeout: "600"
    traefik.ingress.kubernetes.io/proxy-read-timeout: "600"
    traefik.ingress.kubernetes.io/proxy-send-timeout: "600"
    traefik.ingress.kubernetes.io/proxy-body-size: "512m"
  ingressClassName: traefik
spec:
  tls:  
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: tls-nextjs
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}
