name: Build and Deploy

on:
  push:
    tags:
      - strapi*

jobs:
  strapi-build:
    name: "Build strapi app"
    uses: ./.github/workflows/app-build.yml
    with:
        PROJECT_NAME: "strapi"
    secrets:
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        APP_KEYS: ${{ secrets.APP_KEYS }}
        API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
        ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
        TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }}
        DATABASE_CLIENT: ${{ secrets.DATABASE_CLIENT }}
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_SSL: ${{ secrets.DATABASE_SSL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
        CDN_URL: ${{ secrets.CDN_URL }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
