name: Prod deploy workflow

on:
    push:
      tags:
        - 'strapi-v*'

jobs:
  strapi-publish:
    name: "Publish nextjs app"
    uses: ./.github/workflows/publish_image.yml
    with:
        PROJECT_NAME: "strapi"
        FILE_NAME: "strapi.tar"
    secrets:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

  strapi-update-helmchart:
    name: "Update helmchart strapi app"
    needs: strapi-publish
    uses: ./.github/workflows/update_helmchart.yml
    with:
        PROJECT_NAME: "strapi"
    secrets:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
