name: Container Scan Workflow - Post Build

on:
  workflow_call:
    inputs:
        PROJECT_NAME:
          required: true
          type: string

jobs:
  container-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.40.0/trivy_0.40.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.40.0_Linux-64bit.deb
    
      - name: Authenticate with GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan Container Image with Trivy
        run: |
          trivy image --format json --output trivy-report.json ghcr.io/${{ github.repository }}/${{ inputs.PROJECT_NAME }}:latest

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.json
