name: Defectdojo pipeline

on:
  workflow_call:
    inputs:
      DEFECTDOJO_URL:
        required: true
        type: string
      REPORT_PATH:
        required: true
        type: string
      REPORT_NAME:
        required: true
        type: string
      SCAN_TYPE:
        required: true
        type: string
    secrets:
      DEFECTDOJO_TOKEN:
        required: true

jobs:
  publish_to_defectdojo:
    runs-on: ubuntu-latest
    steps:
      - name: Download Reports
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.REPORT_NAME }}

      - name: Download DefectDojo Engagement ID
        uses: actions/download-artifact@v3
        with:
          name: defectdojo-env

      - name: Calculate dates
        id: dates
        run: |
          TODAY=$(date +%Y-%m-%d)
          echo "TODAY=${TODAY}" >> $GITHUB_ENV
  
      - name: Extract Engagement ID
        id: extract_engagement_id
        run: |
          DEFECTDOJO_ENGAGEMENTID=$(cat defectdojo.env | grep DEFECTDOJO_ENGAGEMENTID | cut -d '=' -f2)
          echo "DEFECTDOJO_ENGAGEMENTID=${DEFECTDOJO_ENGAGEMENTID}" >> $GITHUB_ENV

      - name: Publish Report to DefectDojo
        env:
          DEFECTDOJO_ENGAGEMENTID: ${{ env.DEFECTDOJO_ENGAGEMENTID }}
        run: |
          curl --insecure --fail --location --request POST "${{ inputs.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            --header "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
            --form "scan_date=${{ env.TODAY }}" \
            --form "minimum_severity=Info" \
            --form "scan_type=${{ inputs.SCAN_TYPE }}" \
            --form "engagement=${{ env.DEFECTDOJO_ENGAGEMENTID }}" \
            --form "file=@${{ github.workspace }}/${{ inputs.REPORT_PATH }}" \
            --form "close_old_findings=true" \
            --form "environment=Default"