name: Secret Detection Workflow

on:
  workflow_call:

jobs:
  secret-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz | tar -xzC /usr/local/bin gitleaks

      - name: Run Gitleaks
        run: |
          gitleaks detect --redact -v --exit-code=2 --report-format=json --report-path=results.json --log-level=debug --log-opts=-1
            
      - name: Upload Secret Detection Report
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: results.json

      # - name: Run gitleaks
      #   uses: gitleaks/gitleaks-action@v2
      #   env:
      #     GITLEAKS_VERSION: latest
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: chek artifact
      #   run: |
      #       ls

      # - name: Upload Secret Detection Report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: results
      #     path: results.sarif