name: Semgrep SAST

on:
  workflow_call:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: |
        python -m pip install --upgrade pip
        pip install semgrep

    - name: Run Semgrep scan
      run: |
        semgrep --config auto --json --output semgrep-results.json

    - name: Upload Semgrep SAST reports
      uses: actions/upload-artifact@v3
      with:
        name: semgrep-sast-reports
        path: semgrep-results.json
